apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.svcname }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Chart.Name }}
    tier: frontend
  type: LoadBalancer