apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.back.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Chart.Name }}
    tier: mariadb
  clusterIP: None