apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: overweight-hello
spec:
  selector:
    matchLabels:
      app: overweight-hello
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: overweight-hello
        tier: mariadb
    spec:
      containers:
      - image: {{ .Values.mariadb.image }}
        name: mariadb
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: credsecret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credsecret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credsecret
              key: rootpassword
        - name: MYSQL_DATABASE
          value: {{ .Values.mariadb.auth.database }}
        ports:
        - containerPort: 3306
          name: mysql
