apiVersion: v1
kind: Secret
metadata:
  name: credsecret
type: Opaque
data:
  username: {{ .Values.mariadb.auth.username | b64enc }}
  password: {{ .Values.mariadb.auth.username | b64enc }}
  rootpassword: {{ .Values.mariadb.auth.rootPassword | b64enc }}


