name: simple workflow

on:
  push:
    branches:
      - "main"

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_ACCESS_TOKEN }}
  GOOGLE_PROJECT: ${{ vars.GOOGLE_PROJECT }}
  GOOGLE_REGION: ${{ vars.GOOGLE_REGION }}
  IMAGE: overweigh-hello

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_GCP_PROJECT_ID: ${{ vars.GOOGLE_PROJECT }}
      TF_VAR_GCP_PROJECT_REGION: ${{ vars.GOOGLE_REGION }}
      TF_VAR_GCP_PROJECT_ZONE: ${{ vars.GOOGLE_ZONE }}
    outputs:
      repo: ${{ steps.output.outputs.test }}  
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - 
        name: Terraform Init
        run: terraform -chdir=terraform/ init
      - 
        name: Terraform Apply
        run: terraform -chdir=terraform/ apply --auto-approve
      - 
        id: output
        run: echo "test=$(terraform -chdir=terraform/ output docker_repository)" >> $GITHUB_OUTPUT
  push_to_registry:
    name: build and push app
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
      - 
        name: Auth repo
        run: |-
          cat terraform/testkey.json | docker login -u _json_key --password-stdin \ https://${{ needs.terraform.outputs.repo }}
      - 
        name: build
        run: docker build -t ${{ needs.terraform.outputs.repo }}/ ${{ env.IMAGE }}:$(cat app/__version__) app/
      - 
        name: push
        run:  docker push ${{ needs.terraform.outputs.repo }}/ ${{ env.IMAGE }}:$(cat app/__version__)
