name: simple workflow

on:
  push:
    branches:
      - "main"

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_ACCESS_TOKEN }}
  GOOGLE_PROJECT: ${{ vars.GOOGLE_PROJECT }}
  GOOGLE_REGION: ${{ vars.GOOGLE_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_GCP_PROJECT_ID: ${{ vars.GOOGLE_PROJECT }}
      TF_VAR_GCP_PROJECT_REGION: ${{ vars.GOOGLE_REGION }}
      TF_VAR_GCP_PROJECT_ZONE: ${{ vars.GOOGLE_ZONE }}
    output:
      repo: ${{ steps.output.outputs.test }}  
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - 
        name: Terraform Init
        run: terraform -chdir=terraform/ init
      - 
        id: tfapply
        name: Terraform Apply
        run: terraform -chdir=terraform/ outpus --auto-approve
      - 
        id: output
        run: echo "test=$(terraform -chdir=terraform/ output docker_repository)" >> $GITHUB_OUTPUT