name: simple workflow

on:
  push:
    branches:
      - "main"

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_ACCESS_TOKEN }}
  GOOGLE_PROJECT: ${{ vars.GOOGLE_PROJECT }}
  GOOGLE_REGION: ${{ vars.GOOGLE_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_GCP_PROJECT_ID: ${{ vars.GOOGLE_PROJECT }}
      TF_VAR_GCP_PROJECT_REGION: ${{ vars.GOOGLE_REGION }}
      TF_VAR_GCP_PROJECT_ZONE: ${{ vars.GOOGLE_ZONE }}
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Download Terraform state
        uses: devgioele/terraform-state-artifact@v4
        with:
          passphrase: ${{ vars.GOOGLE_REGION }}
          download_upload: download
          statefile_location: ./terraform
      -
        uses: hashicorp/setup-terraform@v1
      - 
        name: Terraform Init
        run: terraform -chdir=terraform/ init
      - 
        name: Terraform Apply
        run: terraform -chdir=terraform/ apply --auto-approve
      - 
        name: Download Terraform state
        uses: devgioele/terraform-state-artifact@v4
        with:
          passphrase: ${{ vars.GOOGLE_REGION }}
          download_upload: download
      - 
        name: Upload Terraform state
        uses: devgioele/terraform-state-artifact@v4
        with:
          passphrase: ${{ vars.GOOGLE_REGION }}
          download_upload: upload
          statefile_location: ./terraform
