name: simple workflow

on:
  push:
    branches:
      - "main"

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_ACCESS_TOKEN }}
  GOOGLE_PROJECT: ${{ vars.GOOGLE_PROJECT }}
  GOOGLE_REGION: ${{ vars.GOOGLE_REGION }}
  IMAGE: overweight-hello

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_GCP_PROJECT_ID: ${{ vars.GOOGLE_PROJECT }}
      TF_VAR_GCP_PROJECT_REGION: ${{ vars.GOOGLE_REGION }}
      TF_VAR_GCP_PROJECT_ZONE: ${{ vars.GOOGLE_ZONE }}
    outputs:
      repo: ${{ steps.output.outputs.test }}  
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - 
        name: Terraform Init
        run: terraform -chdir=terraform/ init
      - 
        name: Terraform Apply
        run: terraform -chdir=terraform/ apply --auto-approve
      - 
        id: output
        run: echo "test=$(terraform -chdir=terraform/ output -raw docker_repository)" >> $GITHUB_OUTPUT
  push_to_registry:
    name: build and push app
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
      - 
        name: build
        run: docker build -t ${{ needs.terraform.outputs.repo }}/${{ env.IMAGE }}:$(cat app/__version__) app/
      -
        name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ needs.terraform.outputs.repo }}
          username: _json_key
          password: ${{ secrets.GCP_ACCESS_TOKEN }}
      - 
        name: push
        run:  docker push us-central1-docker.pkg.dev/fun-with-gcp-386305/repository/overweight-hello:1.1